
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Reydel
 */
public class BREEDING_UPDATEMODAL extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form BREEDING_UPDATEMODAL
     */
    public BREEDING_UPDATEMODAL() {
        setUndecorated(true);
        conn = DBConnection.getConnection();
        initComponents();

        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(LACTATE_YES);
        buttonGroup.add(LACTATE_NO);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BREEDING_CONTAINER = new javax.swing.JPanel();
        BREEDING_DATE = new com.toedter.calendar.JDateChooser();
        BREEDING_BOAR_USED = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        BREEDING_COMMENTS = new javax.swing.JTextArea();
        rSButtonHover11 = new rojeru_san.complementos.RSButtonHover();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BREEDING_BREEDING_TYPE = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        BREEDING_MEDICINE = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rSButtonHover12 = new rojeru_san.complementos.RSButtonHover();
        LACTATE_NO = new javax.swing.JRadioButton();
        LACTATE_YES = new javax.swing.JRadioButton();
        BREEDING_LACTATE = new javax.swing.JLabel();
        BREEDING_EARTAG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BREEDING_CONTAINER.setBackground(new java.awt.Color(26, 46, 53));
        BREEDING_CONTAINER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BREEDING_DATE.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                BREEDING_DATEPropertyChange(evt);
            }
        });
        BREEDING_CONTAINER.add(BREEDING_DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 220, 40));

        BREEDING_BOAR_USED.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BREEDING_CONTAINER.add(BREEDING_BOAR_USED, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 220, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 217, 90));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("BOAR USED");
        BREEDING_CONTAINER.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 220, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 217, 90));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MEDICINE");
        BREEDING_CONTAINER.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 270, 20));

        BREEDING_COMMENTS.setColumns(20);
        BREEDING_COMMENTS.setRows(5);
        jScrollPane4.setViewportView(BREEDING_COMMENTS);

        BREEDING_CONTAINER.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 520, -1));

        rSButtonHover11.setBackground(new java.awt.Color(255, 217, 90));
        rSButtonHover11.setText("UPDATE");
        rSButtonHover11.setColorHover(new java.awt.Color(255, 217, 90));
        rSButtonHover11.setColorText(new java.awt.Color(26, 46, 53));
        rSButtonHover11.setColorTextHover(new java.awt.Color(26, 46, 53));
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        BREEDING_CONTAINER.add(rSButtonHover11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 170, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 217, 90));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PRE-BREEDING STATUS");
        BREEDING_CONTAINER.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 220, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 217, 90));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("EAR TAG");
        BREEDING_CONTAINER.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 220, 20));

        BREEDING_BREEDING_TYPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Al", "Kasta" }));
        BREEDING_CONTAINER.add(BREEDING_BREEDING_TYPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 200, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 217, 90));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("BREEDING DATE");
        BREEDING_CONTAINER.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, 20));
        BREEDING_CONTAINER.add(BREEDING_MEDICINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 200, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 217, 90));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("BREEDING TYPE");
        BREEDING_CONTAINER.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 230, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 217, 90));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("LACTATE");
        BREEDING_CONTAINER.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 270, 20));

        rSButtonHover12.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonHover12.setText("CANCEL");
        rSButtonHover12.setColorHover(new java.awt.Color(255, 217, 90));
        rSButtonHover12.setColorText(new java.awt.Color(26, 46, 53));
        rSButtonHover12.setColorTextHover(new java.awt.Color(26, 46, 53));
        rSButtonHover12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover12ActionPerformed(evt);
            }
        });
        BREEDING_CONTAINER.add(rSButtonHover12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 120, 40));

        LACTATE_NO.setBackground(new java.awt.Color(26, 46, 53));
        LACTATE_NO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LACTATE_NO.setForeground(new java.awt.Color(255, 217, 90));
        LACTATE_NO.setText("NO");
        LACTATE_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LACTATE_NOActionPerformed(evt);
            }
        });
        BREEDING_CONTAINER.add(LACTATE_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        LACTATE_YES.setBackground(new java.awt.Color(26, 46, 53));
        LACTATE_YES.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LACTATE_YES.setForeground(new java.awt.Color(255, 217, 90));
        LACTATE_YES.setText("YES");
        LACTATE_YES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LACTATE_YESActionPerformed(evt);
            }
        });
        BREEDING_CONTAINER.add(LACTATE_YES, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        BREEDING_LACTATE.setText("yes");
        BREEDING_CONTAINER.add(BREEDING_LACTATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 60, 30));

        BREEDING_EARTAG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BREEDING_EARTAG.setForeground(new java.awt.Color(255, 217, 90));
        BREEDING_EARTAG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BREEDING_EARTAG.setText("120312");
        BREEDING_CONTAINER.add(BREEDING_EARTAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BREEDING_CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BREEDING_CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BREEDING_DATEPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_BREEDING_DATEPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_BREEDING_DATEPropertyChange

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed

        String boarUsed = BREEDING_BOAR_USED.getText().trim();
        String comments = BREEDING_COMMENTS.getText().trim();

        if (boarUsed.isEmpty() || !boarUsed.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Invalid input for boarUsed. Please make sure it is a number.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (comments.isEmpty() || !comments.matches("[a-zA-Z0-9 ]*")) {
            JOptionPane.showMessageDialog(null, "Invalid input for comments. Please make sure it contains only alphanumeric characters.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (BREEDING_DATE.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please make sure all fields are not empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            UPDATE_BREEDING();
            //            BREEDING_RETRIEVE_BREEDING_DETAILS();
            //            UPLOAD_NOTIFICATION();
            //            FARROWING_LIST_OF_EARTAGS_CURRENTLY_NOT_FARROWED();
        }
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover12ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_rSButtonHover12ActionPerformed

    private void LACTATE_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LACTATE_NOActionPerformed
        BREEDING_LACTATE.setText("no");
    }//GEN-LAST:event_LACTATE_NOActionPerformed

    private void LACTATE_YESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LACTATE_YESActionPerformed
        BREEDING_LACTATE.setText("yes");
    }//GEN-LAST:event_LACTATE_YESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BREEDING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BREEDING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BREEDING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BREEDING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BREEDING_UPDATEMODAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BREEDING_BOAR_USED;
    private javax.swing.JComboBox<String> BREEDING_BREEDING_TYPE;
    private javax.swing.JTextArea BREEDING_COMMENTS;
    private javax.swing.JPanel BREEDING_CONTAINER;
    private com.toedter.calendar.JDateChooser BREEDING_DATE;
    private javax.swing.JLabel BREEDING_EARTAG;
    private javax.swing.JLabel BREEDING_LACTATE;
    private javax.swing.JTextField BREEDING_MEDICINE;
    private javax.swing.JRadioButton LACTATE_NO;
    private javax.swing.JRadioButton LACTATE_YES;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane4;
    private rojeru_san.complementos.RSButtonHover rSButtonHover11;
    private rojeru_san.complementos.RSButtonHover rSButtonHover12;
    // End of variables declaration//GEN-END:variables

    public void BREEDING_RETRIEVE_BREEDING_SOW(String eartag) {
        BREEDING_EARTAG.setText(eartag);
        try {
            String query = "SELECT boar_used, breeding_date, comments, breeding_type, lactate, medicine FROM breeding WHERE eartag = ?";

            pst = conn.prepareStatement(query);
            pst.setString(1, eartag);
            rs = pst.executeQuery();

            while (rs.next()) {
                String boarUsed = rs.getString("boar_used");
                Date breedingDate = rs.getDate("breeding_date");
                String comments = rs.getString("comments");
                String breedingType = rs.getString("breeding_type");
                String lactate = rs.getString("lactate");
                String medicine = rs.getString("medicine");

                BREEDING_BOAR_USED.setText(boarUsed);
                BREEDING_DATE.setDate(breedingDate);
                BREEDING_COMMENTS.setText(comments);
                BREEDING_BREEDING_TYPE.setSelectedItem(breedingType);

                if (lactate.equals("Yes")) {
                    LACTATE_YES.setSelected(true);
                } else {
                    LACTATE_NO.setSelected(true);
                }
                BREEDING_MEDICINE.setText(medicine);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void UPDATE_BREEDING() {
        Date selectedDate = BREEDING_DATE.getDate();
        String dateString = new java.sql.Date(selectedDate.getTime()).toString();

        try {
            String sql = "UPDATE breeding SET boar_used = ?, breeding_date = ?, comments = ?, breeding_type = ?, lactate = ?, medicine = ? WHERE eartag = ?";

            pst = conn.prepareStatement(sql);

            pst = conn.prepareStatement(sql);
            pst.setString(1, BREEDING_BOAR_USED.getText());
            pst.setString(2, dateString);
            pst.setString(3, BREEDING_COMMENTS.getText());
            pst.setString(4, (String) BREEDING_BREEDING_TYPE.getSelectedItem());
            pst.setString(5, BREEDING_LACTATE.getText());
            pst.setString(6, BREEDING_MEDICINE.getText());
            pst.setString(7, BREEDING_EARTAG.getText());

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {

                JOptionPane.showMessageDialog(null, "Updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update sow.");
            }

            BREEDING_BOAR_USED.setText("");
            BREEDING_DATE.setDate(null);
            BREEDING_COMMENTS.setText("");
            BREEDING_BREEDING_TYPE.setSelectedIndex(0);
            LACTATE_YES.setSelected(true);
            BREEDING_MEDICINE.setText("");
            BREEDING_EARTAG.setText("");

            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
