
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Reydel
 */
public class CREATEACCOUNT extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form CREATEACCOUNT
     */
    public CREATEACCOUNT() {

        setUndecorated(true);
        conn = DBConnection.getConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        jLabel5 = new javax.swing.JLabel();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();
        jLabel4 = new javax.swing.JLabel();
        CREATE_FULLNAME = new javax.swing.JTextField();
        CREATE_USERNAME = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CREATE_WARNING = new javax.swing.JLabel();
        CREATE_PASSWORD = new javax.swing.JPasswordField();
        CREATE_REPASSWORD = new javax.swing.JPasswordField();
        CREATE_ACCOUNT_TYPE = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(26, 46, 53));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 217, 90));
        jLabel1.setText("Create account");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 290, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 217, 90));
        jLabel2.setText("FULL NAME");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 217, 90));
        jLabel3.setText("ACCOUNT TYPE");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 130, 20));

        rSButtonHover1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover1.setText("Cancel");
        rSButtonHover1.setColorHover(new java.awt.Color(255, 217, 90));
        rSButtonHover1.setColorText(new java.awt.Color(26, 46, 53));
        rSButtonHover1.setColorTextHover(new java.awt.Color(26, 46, 53));
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/eyes.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 50, 40));

        rSButtonHover2.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover2.setText("CREATE ACCOUNT");
        rSButtonHover2.setColorHover(new java.awt.Color(255, 217, 90));
        rSButtonHover2.setColorText(new java.awt.Color(26, 46, 53));
        rSButtonHover2.setColorTextHover(new java.awt.Color(26, 46, 53));
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 217, 90));
        jLabel4.setText("ENTER USERNAME");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, 20));
        jPanel3.add(CREATE_FULLNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 230, 30));
        jPanel3.add(CREATE_USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 230, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 217, 90));
        jLabel6.setText("ENTER PASSWORD");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, 20));

        CREATE_WARNING.setForeground(new java.awt.Color(255, 217, 90));
        CREATE_WARNING.setText(" ");
        jPanel3.add(CREATE_WARNING, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 140, 20));
        jPanel3.add(CREATE_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 242, 230, 30));

        CREATE_REPASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CREATE_REPASSWORDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CREATE_REPASSWORDKeyTyped(evt);
            }
        });
        jPanel3.add(CREATE_REPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 230, 30));

        CREATE_ACCOUNT_TYPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretary", "Operation Manger" }));
        jPanel3.add(CREATE_ACCOUNT_TYPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 230, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 217, 90));
        jLabel7.setText("RE-ENTER PASSWORD");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        CREATE_PASSWORD.setEchoChar((char) 0);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        CREATE_PASSWORD.setEchoChar('*');
    }//GEN-LAST:event_jLabel5MouseReleased

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
       CREATE_ACCOUNT();
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void CREATE_REPASSWORDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CREATE_REPASSWORDKeyTyped

    }//GEN-LAST:event_CREATE_REPASSWORDKeyTyped

    private void CREATE_REPASSWORDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CREATE_REPASSWORDKeyReleased
        checkPasswordMatch();
    }//GEN-LAST:event_CREATE_REPASSWORDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREATEACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREATEACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREATEACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREATEACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CREATEACCOUNT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CREATE_ACCOUNT_TYPE;
    private javax.swing.JTextField CREATE_FULLNAME;
    private javax.swing.JPasswordField CREATE_PASSWORD;
    private javax.swing.JPasswordField CREATE_REPASSWORD;
    private javax.swing.JTextField CREATE_USERNAME;
    private javax.swing.JLabel CREATE_WARNING;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    // End of variables declaration//GEN-END:variables

    private void checkPasswordMatch() {
        if (!Arrays.equals(CREATE_REPASSWORD.getPassword(), CREATE_PASSWORD.getPassword())) {
            CREATE_WARNING.setText("Passwords do not match");
        } else {
            CREATE_WARNING.setText("Passwords match");
        }
    }

    private void CREATE_ACCOUNT() {
        try {

            String sql = "INSERT INTO accounts (fullname, username, password, account_type) VALUES (?, ?, ?, ?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, CREATE_FULLNAME.getText());
            pst.setString(2, CREATE_USERNAME.getText());
            String password = new String(CREATE_REPASSWORD.getPassword());
            pst.setString(3, password);
            pst.setString(4, (String) CREATE_ACCOUNT_TYPE.getSelectedItem());

            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Succesfully created an account");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null, "Error");

        }
    }

}
