
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Reydel
 */
public class FARROWING_UPDATEMODAL extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form FARROWING_UPDATEMODAL
     */
    public FARROWING_UPDATEMODAL() {
        setUndecorated(true);
        conn = DBConnection.getConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        FARROWING_ABW = new javax.swing.JTextField();
        FARROWING_MORT = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        FARROWING_REMARKS = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        FARROWING_ACTUAL = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        FARROWING_MALE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        FARROWING_FEMALE = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        FARROWING_TOTAL_PIGLETS = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        UPDATE_FARROWING_EARTAG = new javax.swing.JLabel();
        rSButtonHover13 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover11 = new rojeru_san.complementos.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(26, 46, 53));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 217, 90));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ABW");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, -1));

        FARROWING_ABW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(FARROWING_ABW, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 190, 40));

        FARROWING_MORT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(FARROWING_MORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 190, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 217, 90));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("MORT");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 190, -1));

        FARROWING_REMARKS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(FARROWING_REMARKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 190, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 217, 90));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("REMARKS");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 190, -1));
        jPanel11.add(FARROWING_ACTUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 217, 90));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ACTUAL DATE");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 217, 90));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("M");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, -1));

        FARROWING_MALE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FARROWING_MALE.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                FARROWING_MALEInputMethodTextChanged(evt);
            }
        });
        FARROWING_MALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FARROWING_MALEActionPerformed(evt);
            }
        });
        FARROWING_MALE.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FARROWING_MALEPropertyChange(evt);
            }
        });
        jPanel11.add(FARROWING_MALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 217, 90));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("F");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 60, -1));

        FARROWING_FEMALE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FARROWING_FEMALE.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                FARROWING_FEMALEInputMethodTextChanged(evt);
            }
        });
        FARROWING_FEMALE.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FARROWING_FEMALEPropertyChange(evt);
            }
        });
        jPanel11.add(FARROWING_FEMALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, 30));

        jButton9.setText("=");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 50, 30));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FARROWING_TOTAL_PIGLETS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FARROWING_TOTAL_PIGLETS.setForeground(new java.awt.Color(255, 217, 90));
        FARROWING_TOTAL_PIGLETS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(FARROWING_TOTAL_PIGLETS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 40));

        jPanel11.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 40));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 217, 90));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("TOTAL BORN");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 120, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 217, 90));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("EAR TAG");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, -1));

        UPDATE_FARROWING_EARTAG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UPDATE_FARROWING_EARTAG.setForeground(new java.awt.Color(255, 217, 90));
        UPDATE_FARROWING_EARTAG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE_FARROWING_EARTAG.setText("120312");
        jPanel11.add(UPDATE_FARROWING_EARTAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 150, 50));

        rSButtonHover13.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonHover13.setText("CANCEL");
        rSButtonHover13.setColorHover(new java.awt.Color(255, 217, 90));
        rSButtonHover13.setColorText(new java.awt.Color(26, 46, 53));
        rSButtonHover13.setColorTextHover(new java.awt.Color(26, 46, 53));
        rSButtonHover13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover13ActionPerformed(evt);
            }
        });
        jPanel11.add(rSButtonHover13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 120, 40));

        rSButtonHover11.setBackground(new java.awt.Color(255, 217, 90));
        rSButtonHover11.setText("UPDATE");
        rSButtonHover11.setColorHover(new java.awt.Color(255, 217, 90));
        rSButtonHover11.setColorText(new java.awt.Color(26, 46, 53));
        rSButtonHover11.setColorTextHover(new java.awt.Color(26, 46, 53));
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        jPanel11.add(rSButtonHover11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FARROWING_MALEInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_FARROWING_MALEInputMethodTextChanged

    }//GEN-LAST:event_FARROWING_MALEInputMethodTextChanged

    private void FARROWING_MALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FARROWING_MALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FARROWING_MALEActionPerformed

    private void FARROWING_MALEPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FARROWING_MALEPropertyChange

    }//GEN-LAST:event_FARROWING_MALEPropertyChange

    private void FARROWING_FEMALEInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_FARROWING_FEMALEInputMethodTextChanged

    }//GEN-LAST:event_FARROWING_FEMALEInputMethodTextChanged

    private void FARROWING_FEMALEPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FARROWING_FEMALEPropertyChange

    }//GEN-LAST:event_FARROWING_FEMALEPropertyChange

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (FARROWING_MALE.getText().isEmpty() || !FARROWING_MALE.getText().matches("\\d+")
                || FARROWING_FEMALE.getText().isEmpty() || !FARROWING_FEMALE.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please make sure all fields are not empty and have the correct format.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int maleCount = FARROWING_MALE.getText().isEmpty() ? 0 : Integer.parseInt(FARROWING_MALE.getText());
            int femaleCount = FARROWING_FEMALE.getText().isEmpty() ? 0 : Integer.parseInt(FARROWING_FEMALE.getText());
            int total = maleCount + femaleCount;
            FARROWING_TOTAL_PIGLETS.setText(Integer.toString(total));
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void rSButtonHover13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover13ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_rSButtonHover13ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        UPDATE_FARROWING();
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FARROWING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FARROWING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FARROWING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FARROWING_UPDATEMODAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FARROWING_UPDATEMODAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FARROWING_ABW;
    private com.toedter.calendar.JDateChooser FARROWING_ACTUAL;
    private javax.swing.JTextField FARROWING_FEMALE;
    private javax.swing.JTextField FARROWING_MALE;
    private javax.swing.JTextField FARROWING_MORT;
    private javax.swing.JTextField FARROWING_REMARKS;
    private javax.swing.JLabel FARROWING_TOTAL_PIGLETS;
    private javax.swing.JLabel UPDATE_FARROWING_EARTAG;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel6;
    private rojeru_san.complementos.RSButtonHover rSButtonHover11;
    private rojeru_san.complementos.RSButtonHover rSButtonHover13;
    // End of variables declaration//GEN-END:variables

    public void FARROWING_RETRIEVE_RECORD(String eartag) {
        UPDATE_FARROWING_EARTAG.setText(eartag);
        try {
            String query = "SELECT farrowing_actualdate, female_piglets, male_piglets, total_piglets, abw, mortality, remarks FROM farrowing_records WHERE eartag = ?";

            pst = conn.prepareStatement(query);
            pst.setString(1, eartag);
            rs = pst.executeQuery();

            while (rs.next()) {
                Date farrowingDate = rs.getDate("farrowing_actualdate");
                int femalePiglets = rs.getInt("female_piglets");
                int malePiglets = rs.getInt("male_piglets");
                int totalPiglets = rs.getInt("total_piglets");
                double abw = rs.getDouble("abw");
                int mortality = rs.getInt("mortality");
                String remarks = rs.getString("remarks");

                FARROWING_ACTUAL.setDate(farrowingDate);
                FARROWING_FEMALE.setText(String.valueOf(femalePiglets));
                FARROWING_MALE.setText(String.valueOf(malePiglets));
                FARROWING_TOTAL_PIGLETS.setText(String.valueOf(totalPiglets));
                FARROWING_ABW.setText(String.valueOf(abw));
                FARROWING_MORT.setText(String.valueOf(mortality));
                FARROWING_REMARKS.setText(remarks);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void UPDATE_FARROWING() {
        Date selectedDate = FARROWING_ACTUAL.getDate();
        String dateString = new java.sql.Date(selectedDate.getTime()).toString();

        try {
            String query = "UPDATE farrowing_records SET farrowing_actualdate = ?, female_piglets = ?, male_piglets = ?, total_piglets = ?, abw = ?, mortality = ?, remarks = ? WHERE eartag = ?";

            pst = conn.prepareStatement(query);
            pst.setString(1, dateString);
            pst.setInt(2, Integer.parseInt(FARROWING_FEMALE.getText()));
            pst.setInt(3, Integer.parseInt(FARROWING_MALE.getText()));
            pst.setInt(4, Integer.parseInt(FARROWING_TOTAL_PIGLETS.getText()));
            pst.setDouble(5, Double.parseDouble(FARROWING_ABW.getText()));
            pst.setInt(6, Integer.parseInt(FARROWING_MORT.getText()));
            pst.setString(7, FARROWING_REMARKS.getText());
            pst.setString(8, UPDATE_FARROWING_EARTAG.getText());

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {

                JOptionPane.showMessageDialog(null, "Updated successfully!");

            } else {
                JOptionPane.showMessageDialog(null, "Failed to update sow.");
            }
            FARROWING_ACTUAL.setDate(null);
            FARROWING_FEMALE.setText("");
            FARROWING_MALE.setText("");
            FARROWING_TOTAL_PIGLETS.setText("");
            FARROWING_ABW.setText("");
            FARROWING_MORT.setText("");
            FARROWING_REMARKS.setText("");
            UPDATE_FARROWING_EARTAG.setText("");
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
